
CREATE TABLE orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    shopId INT NOT NULL,
    clientId INT NOT NULL,
    paymentMethod VARCHAR(20) NOT NULL,
    paid BOOLEAN DEFAULT 0,
    paidAt DATETIME,
    items TEXT,
    deposit INT
);


CREATE TABLE clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    premises VARCHAR(20) NOT NULL,
    clientName VARCHAR(20) NOT NULL,
    mall VARCHAR(20) NOT NULL,
    phoneNumber INT
);

CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    productName VARCHAR(20) NOT NULL,
    unitValue INT
);