CREATE TABLE `users` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` timestamp NULL DEFAULT current_timestamp(), `userName` varchar(50), `pass` varchar(50), PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `products` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` timestamp NOT NULL DEFAULT current_timestamp(), `productName` varchar(40), `unitValue` int, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `orders` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` timestamp NOT NULL DEFAULT current_timestamp(), `shopId` int NOT NULL, `clientId` int NOT NULL, `paymentMethod` varchar(20), `paid` tinyint(1) DEFAULT '0', `isAbandoned` tinyint(1) DEFAULT '0', `abandonedAt` datetime, `abandonedBy` varchar(255), `abandonReason` text, `paidAt` datetime, `items` text, `deposit` int, `collectedBy` varchar(20), PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `clients` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` timestamp NOT NULL DEFAULT current_timestamp(), `premises` varchar(20) NOT NULL, `clientName` varchar(20) NOT NULL, `mall` varchar(20) NOT NULL, `phoneNumber` varchar(20), PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `deposits` (`depositId` int NOT NULL AUTO_INCREMENT, `depositCreatedAt` timestamp NOT NULL DEFAULT current_timestamp(), `orderId` int NOT NULL, `clientId` int NOT NULL, `paymentMethod` varchar(20), `depositValue` int NOT NULL, `lastDeposit` int NOT NULL, `newDeposit` int NOT NULL, PRIMARY KEY (`depositId`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `order_snapshots` (`id` int NOT NULL AUTO_INCREMENT, `orderId` int NOT NULL, `snapshotDate` date NOT NULL, `itemsGz` mediumblob, `deposit` int DEFAULT NULL, `paid` tinyint(1) DEFAULT '0', `paidAt` datetime DEFAULT NULL, `createdAt` timestamp NOT NULL DEFAULT current_timestamp(), PRIMARY KEY (`id`), UNIQUE KEY `uq_snapshot_order_day` (`orderId`,`snapshotDate`), KEY `idx_snapshot_date` (`snapshotDate`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `order_restores` (`id` int NOT NULL AUTO_INCREMENT, `orderId` int NOT NULL, `snapshotId` int NOT NULL, `restoredFromDate` date NOT NULL, `restoredBy` varchar(255) DEFAULT NULL, `restoredAt` datetime DEFAULT NULL, `createdAt` timestamp NOT NULL DEFAULT current_timestamp(), PRIMARY KEY (`id`), KEY `idx_restores_order` (`orderId`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
